ctln12/unicorn326

config/environments/production.rb
added brainiak.io as host in config/env/production/production
=> add brainiak.io as host

app/controllers/application_controller.rb, app/controllers/pages_controller.rb, app/controllers/students/confirmations_controller.rb, app/controllers/students/omniauth_callbacks_controller.rb, app/controllers/students/passwords_controller.rb, app/controllers/students/registrations_controller.rb, app/controllers/students/sessions_controller.rb, app/controllers/students/unlocks_controller.rb, app/models/student.rb, app/models/user.rb, app/views/shared/_navbar.html.erb, app/views/students/confirmations/new.html.erb, app/views/students/mailer/confirmation_instructions.html.erb, app/views/students/mailer/email_changed.html.erb, app/views/students/mailer/password_change.html.erb, app/views/students/mailer/reset_password_instructions.html.erb, app/views/students/mailer/unlock_instructions.html.erb, app/views/students/passwords/edit.html.erb, app/views/students/passwords/new.html.erb, app/views/students/registrations/edit.html.erb, app/views/students/registrations/new.html.erb, app/views/students/sessions/new.html.erb, app/views/students/shared/_error_messages.html.erb, app/views/students/shared/_links.html.erb, app/views/students/unlocks/new.html.erb, config/initializers/devise.rb, config/routes.rb, db/migrate/20191230085531_devise_create_students.rb, db/schema.rb, test/models/student_test.rb
installed Devise for student (removed user, added views and controllers)
missing Country field, photo_url handler & wallet ID
=> student devise part 1

app/models/student.rb, app/views/devise/registrations/new.html.erb, app/views/students/registrations/new.html.erb, app/views/students/sessions/new.html.erb, app/views/students/shared/_links.html.erb, db/schema.rb
Change a few thing to resolve conflicts generated by merge of student/devise and tutor devise implementation
=> conflict modification due to merger tutor and student

app/controllers/application_controller.rb, app/views/devise/registrations/new.html.erb, app/views/shared/_navbar.html.erb, app/views/tutors/registrations/new.html.erb, app/views/tutors/sessions/new.html.erb, app/views/tutors/shared/_links.html.erb, db/migrate/20191230125336_add_date_of_birth_to_tutors.rb, db/schema.rb
Resolved conflicts after merging tutor and student models
Add date of birth column to tutors table
Add date of birth as permitted parameter for tutors
Add date of birth field to tutor sign up form
=> Tutor conflicts resolved

Gemfile, Gemfile.lock, app/views/students/registrations/new.html.erb, app/views/tutors/registrations/new.html.erb
Added country select gem into students & tutors profiles
=> added country select gem for students and tutors

app/models/subject.rb, db/migrate/20200103163912_create_subjects.rb, test/models/subject_test.rb
=> created subject model

app/models/spoken_language.rb, db/migrate/20200103164339_create_spoken_languages.rb, test/models/spoken_language_test.rb
=> created spoken_language model

app/models/wallet.rb, db/migrate/20200103163610_create_wallets.rb, test/models/wallet_test.rb
=> created wallet model

app/views/students/registrations/new.html.erb, app/views/tutors/registrations/new.html.erb, db/schema.rb
Run pending migrations
Add label for country input
=> Pull request small fixes

app/models/student.rb, app/models/tutor.rb, app/views/students/registrations/new.html.erb
Student:
- delete validation for phone number
- uncomment validation for country
- reorder validations
Tutor:
- add validation for date of birth
- add validation for country
Student sign up view:
- move email and password fields to bottom
=> Student tutor validations and student sign up view

app/javascript/packs/application.js, app/views/layouts/application.html.erb, package.json, yarn.lock
Solve problem with dropdown menu (log out) in navbar by yarn installing bootstrap-select
=> Navbar log out

db/migrate/20200106102605_remove_subjects_to_tutors.rb, db/migrate/20200106103134_add_subjects_to_tutors.rb, db/migrate/20200106103203_add_spoken_languages_to_tutors.rb, db/migrate/20200106103541_add_wallets_to_students.rb, db/migrate/20200106103556_add_wallets_to_tutors.rb, db/schema.rb
Added  to Students:
Wallets foreign key
Added to Tutors:
Wallets foreign key
Subjects foreign key
Spoken_languages foreign key
=> added wallets subjects & spoken languages as foreign keys

db/migrate/20200107151014_remove_fields_to_tutors.rb, db/schema.rb
removed references to subjects and spoke-languages in tutor model
=> removed references to subjects and spoke-languages

db/seeds.rb
As explained in the previous pull request #23, this one fixes the problem when running the seed.
I changed Subjects for Subject in the part creating the subjects and Subjects for Language in the part creating the languages.
It seems to be working now.
=> Modify seed for subjects and languages

db/seeds.rb
Reset subjects and languages before creating seed
=> destroy all subjects and languages before seeding

app/controllers/languages_controller.rb, app/controllers/subjects_controller.rb, app/views/languages/index.html.erb, app/views/subjects/index.html.erb, config/routes.rb, test/controllers/languages_controller_test.rb, test/controllers/subjects_controller_test.rb
Generated controllers subjects and languages
Add skip before action authentication for students and tutors only for index
Implemented methods index
Implemented views
=> Subjects languages controllers

db/seeds.rb
Add destruction of the content of tables before creating new content
Add creation of 2 students and 5 tutors
=> create 2 students and 5 tutors

app/controllers/application_controller.rb, app/controllers/languages_controller.rb, app/controllers/pages_controller.rb, app/controllers/students_controller.rb, app/controllers/subjects_controller.rb, app/controllers/tutors_controller.rb, app/views/students/show.html.erb, app/views/tutors/show.html.erb, config/routes.rb, test/controllers/students_controller_test.rb, test/controllers/tutors_controller_test.rb
- Add show paths for students and tutors
- Generate students and tutors controllers (without devise) with method show and implement it
- Create students and tutors views and display first name and last name
- Add methods after sign up and after sign in to redirect to student or tutor show (instead of redirecting to root by default)
=> Students and tutors show

app/controllers/spoken_languages_controller.rb, app/views/shared/_navbar.html.erb, app/views/spoken_languages/new.html.erb, app/views/tutors/show.html.erb, config/routes.rb, test/controllers/spoken_languages_controller_test.rb
*Routes*
- Add new routes for spoken languages controller and actions new and create
*Controller*
- Generate spoken languages controller with methods new and create
*View*
- Create spoken languages new view with simple form for to add multiple languages
- Add button to add languages and display spoken languages
- Add different dashboard links for students and tutors to navbar
=> Tutor spoken languages

app/controllers/taught_lessons_controller.rb, app/views/pages/home.html.erb, app/views/taught_lessons/new.html.erb, app/views/tutors/registrations/edit.html.erb, config/routes.rb, test/controllers/taught_lessons_controller_test.rb
added taught lessons controller
=> Taught lessons controller

app/controllers/taught_lessons_controller.rb
taught_lessons_controller 
Removed  "Skip_before_action authenticate..." 
Refactored def create
=> removed skip_before_action... and refactored def create

app/controllers/taught_lessons_controller.rb, app/models/taught_lesson.rb, app/views/pages/home.html.erb, app/views/taught_lessons/edit.html.erb, app/views/taught_lessons/new.html.erb, app/views/tutors/registrations/new.html.erb, app/views/tutors/show.html.erb, config/routes.rb
Tutor show
Added Link to add and delete to Subjects 
Added View "add" (Subjects)
=> Edit registration tutor

db/seeds.rb
added spoken languages and subjects linked with tutors in the seed
=> added spoken languages and subjects linked with tutors in the seed

app/controllers/spoken_languages_controller.rb, app/models/spoken_language.rb, app/views/shared/_navbar.html.erb, app/views/spoken_languages/new.html.erb, app/views/taught_lessons/new.html.erb, app/views/tutors/registrations/edit.html.erb, app/views/tutors/show.html.erb, config/routes.rb
- Implemented the feature allowing a tutor to add languages to profile
- Added delete button to languages list
- Added my profile link to navbar
- Reordered fields of edit tutor form
=> Add spoken languages

app/controllers/tutors_controller.rb, app/views/pages/home.html.erb, app/views/shared/_navbar.html.erb, app/views/tutors/index.html.erb, config/routes.rb, db/seeds.rb
For tutors#index:
- add route
- add method to controller
- add view
On home page:
- add button to tutors index view
In navbar:
- add link to tutors index
- add root path to logo
Seed:
- fix philosophy typo
=> Tutors index

app/controllers/application_controller.rb, app/controllers/tutors_controller.rb, app/views/layouts/application.html.erb, app/views/shared/_navbar.html.erb, app/views/tutors/show.html.erb
- Implemented tutors show view
- Add bootstrap container for each page
- Remove after sign up/in methods
- Remove before action authenticate tutor
- Add before action authenticate student
- Add find tutor link to navbar when signed in
=> Tutors show

app/views/tutors/index.html.erb, app/views/tutors/show.html.erb
Using `ISO3166::Country.find_country_by_alpha2("<country_code>")`
=> translate country code to full name

app/controllers/tutors_controller.rb, app/views/tutors/index.html.erb
- Add for to filter tutors
- Modify method index to filter tutors
=> Filter tutors

app/controllers/tutors_controller.rb, app/models/tutor.rb, app/views/tutors/index.html.erb
Filter menu:
- Add option to save selected input
- Remove multiple select
- Add include blank All
- Add style to make sticky on scroll
Tutor controller:
- refactor index method using joins and where
- refactor again to work without multiple select and with include blank
Tutor model:
- Add association has many subjects through taught lessons
- Add association has many languages through spoken languages
=> Filter tutors improved

Gemfile, Gemfile.lock, db/seeds.rb
add extra 100 tutors 
+
some: languages, subjects, taught lessons, spoken languages
=> Seed updates

app/views/tutors/show.html.erb
Tutors show view:
- add buttons Send a message and Book a lesson without defining real paths
=> Tutors show msg book btns

app/views/shared/_navbar.html.erb, app/views/students/registrations/edit.html.erb
Edited student path 
Added same fields as Sign Up + Link to profile
=> edited student path

app/controllers/spoken_languages_controller.rb, app/controllers/taught_lessons_controller.rb, app/controllers/tutors/registrations_controller.rb, app/controllers/tutors_controller.rb, app/views/shared/_navbar.html.erb, app/views/tutors/profile.html.erb, app/views/tutors/registrations/edit.html.erb, config/routes.rb
Navbar:
- change path of 'My profile' link to `profile_tutors_path`
Routes:
- add collection `profile` to resources for tutors
Tutors controller:
- add method profile
In app > views > tutors:
- create `profile.html.erb` and add 'edit' button
In app > controllers > tutors > `registrations_controller`:
- add protected method to redirect to profile view after update
In `taught_lessons controller` and `spoken_languages controller` files:
- change redirect to `edit_tutor_registration_path` for methods `create` and `destroy`
In `edit_tutor_registration_path` file:
- add subjects and languages to be edited
=> Tutor profile

app/controllers/bookings_controller.rb, app/models/booking.rb, app/models/subject.rb, app/views/bookings/index.html.erb, app/views/shared/_navbar.html.erb, config/routes.rb, db/migrate/20200117104150_add_paid_at_to_bookings.rb, db/migrate/20200117141101_add_subject_to_bookings.rb, db/migrate/20200117145048_change_type_of_date_in_bookings.rb, db/schema.rb, db/seeds.rb, test/controllers/bookings_controller_test.rb
Create new:
- route `'/booking'`, controller bookings and `index.html.erb`
Models:
- booking: add association `belongs to subject`
- subject: add association `has many bookings`
Bookings controller:
- add before action `authenticate tutor` only for index
Bookings table:
- add column `paid_at` and reference `subject_id`
- change column type of date: `date` to `datetime`
Seed:
- create 5 bookings: students Alice and Bob, tutor Pierre
Navbar:
- change `dashboard` link to `lessons`
=> Tutors bookings index

app/assets/javascripts/application.js, app/controllers/bookings_controller.rb, app/models/booking.rb, app/views/bookings/index.html.erb, app/views/bookings/new.html.erb, app/views/tutors/show.html.erb, config/routes.rb, db/migrate/20200118171525_change_type_of_duration_in_bookings.rb, db/migrate/20200120134223_add_language_to_bookings.rb, db/schema.rb, db/seeds.rb
Table bookings:
- added columns subject id, paid at, language id
- changed type of column date
Model-Controller-View:
- added association belongs to a subject and to a language
- implemented method new and create using strong params
- created booking form
- used javascript to update total price when changing duration
- used readonly option to show fields price per hour and total price but unable modifications
- hid fields student id and tutor id
Seed:
- added language data to created bookings
=> Student book lesson

app/views/job_posts/show.html.erb, app/views/shared/_navbar.html.erb, db/seeds.rb
In seed:
- remove conflicts tags not noticed
- modified order of destroyed tables
In job show view:
- changed argument job_post to @job_post in Reply button
In navbar:
- move two links out of conditional
=> Fix seed, job post show view and navbar

app/controllers/bookings_controller.rb, app/views/bookings/index.html.erb, app/views/bookings/new.html.erb, app/views/bookings/show.html.erb, config/routes.rb, db/seeds.rb
Bookings index:
- modify conditions to show the adequate button and text
Bookings show:
- add route
- define method in controller
- add content in view
- use same logic as index view for button
Seeds:
- modify creation of bookings
=> Bookings show

app/views/bookings/index.html.erb, app/views/bookings/show.html.erb, app/views/pages/home.html.erb
Modify conditionals to display/hide buttons and warning messages
=> Bookings buttons changes

app/controllers/bookings_controller.rb, app/views/bookings/index.html.erb, app/views/bookings/show.html.erb
Add actions to buttons cancel, accept and proceed to payment
=> Cancel booking

app/controllers/application_controller.rb, app/models/tutor.rb, app/views/tutors/registrations/new.html.erb
Changed permitted field and collection with all currencies in teacher signup
=> Currencyproblem

.gitignore, app/views/tutors/profile.html.erb, app/views/tutors/show.html.erb
- remove and add ngrok to gitignore file
- add reviews to tutor's profile
=> ngrok and reviews

app/controllers/tutors/registrations_controller.rb, app/controllers/wallets_controller.rb, app/models/currency.rb, app/models/tutor.rb, app/models/wallet.rb, app/views/shared/_navbar.html.erb, app/views/wallets/show.html.erb, config/routes.rb, db/migrate/20200218142359_change_references_from_wallets.rb, db/migrate/20200218155521_remove_wallet_id_from_tutors.rb, db/schema.rb, db/seeds.rb
=> Walletfixing

Gemfile, Gemfile.lock, app/mailers/application_mailer.rb, app/mailers/student_mailer.rb, app/mailers/tutor_mailer.rb, app/models/student.rb, app/models/tutor.rb, app/views/student_mailer/welcome.html.erb, app/views/tutor_mailer/welcome.html.erb, config/environments/development.rb, test/mailers/previews/student_mailer_preview.rb, test/mailers/previews/tutor_mailer_preview.rb, test/mailers/student_mailer_test.rb, test/mailers/tutor_mailer_test.rb
Added Welcome notification to Tutors and Students in local environment
=> added email welcome notification

package.json, yarn.lock
=> update all dependencies

config/environments/production.rb
Modify `config > environments > production.rb`:
- replaced `:uglifier`with `Uglifier.new(harmony: true)`
=> enable ES6 syntax

config/puma.rb
Commented line 19 regarding pidfile in `config > puma.rb`
=> Fix Heroku bug

app/assets/stylesheets/lessons/_show.scss
Change css selector for buttons
=> Fix the problem with the display of the filters buttons

db/seeds.rb
Reduction of tutors and students created
=> diminished seed

config/environments/production.rb
=> modified config environment production.rb

config/environments/production.rb
added new username and password to sendgrid smtp
=> changed username and password

app/mailers/application_mailer.rb
In `app > mailers > application_mailer.rb`:
- changed email 'info@brainiak.io' to personal existing one
=> modify mail sender to existing one

config/environment.rb
=> changed domain name

app/assets/javascripts/lessons/agora.js
in app > assets > javascript > lessons > `agora.js`
=> modify variable options

app/assets/javascripts/channels/chat_channel.js
extend conditional to all code to avoid errors and problems with agora
=> fix problems with agora

app/controllers/bookings_controller.rb
In `app > controllers > bookings_controller.rb`:
- in the create method, added chat creation after booking creation and before redirecting
=> Chat creation upon booking creation

app/assets/javascripts/application.js, app/assets/javascripts/bookings/update_date_price.js
Fix problems with end date not updating upon changing start date and price not updating upon time change: moved code from `app > assets > javascripts > application.js` to `app > assets > javascripts > bookings > update_date_price.js`
=> Booking date & time problem

app/controllers/reviews_controller.rb, app/models/review.rb
Modified validation of review. 
if message doesn't respect minimum characters. System shows error message and stays on the same page. When min characters are respected review is saved
=> modified review validation

app/assets/javascripts/channels/chat_channel.js, app/controllers/chats_controller.rb, app/views/chats/index.html.erb, app/views/layouts/application.html.erb, app/views/shared/_navbar.html.erb, config/routes.rb
- Created new index route, method and view for chats
- Added chats index to navbar
- Renamed Lessons to Bookings in navbar
- Changed url of jquery script to start with https in head
- Removed console log in chat_channel.js
=> add chats to navbar

app/assets/javascripts/lessons/agora.js, app/assets/stylesheets/lessons/_show.scss, app/views/lessons/show.html.erb
- Remove back button on lesson's show page
- Add redirection to new review creation to end button
- Modify stylesheet and javascript consequently
=> redirect when clicking on end lesson

app/views/lessons/show.html.erb
After the lesson:
- if the user is a student, the end button sends to the review creation page
- but if the user is a tutor, it sends to the bookings index page
=> modify path of button end whether user is a student or a tutor

app/javascript/packs/lesson.js
Commented logs in lesson.js file
=> comment logs

app/javascript/packs/lesson.js
=> Revert "comment logs"

app/controllers/bookings_controller.rb, app/controllers/wallets_controller.rb, app/services/stripe_checkout_session_service.rb, app/views/payments/new.html.erb, config/routes.rb
Added details on the booking into Checkout page
Added description into Stripe checkout page
and when payment goes through successfully it credits the amount into the wallet
=> Walletlink

app/views/bookings/show.html.erb
proceed button is now in orange color
=> proceed to payment button is now in orange

db/seeds.rb
=> pierre has now 0 eur in the wallet

db/migrate/20200618170209_create_active_storage_tables.active_storage.rb, db/schema.rb
=> added active storage

app/controllers/tutors_controller.rb, app/views/tutors/index.html.erb
I simplified the search in the index action of the tutors controller. Isn't it much better ? ;)
In the end I didn't add more filters.
_Next up: I will try to add Algolia for the search and InstantSearch for the filters._
=> Refactor index search

package.json, yarn.lock
It was working yesterday but after pulling to master the merged pull request, trying to push to Heroku failed.
I think I found the bug: I installed `algoliasearch` and `instantsearch.js` packages. 🤞
=> Fix problem with Algolia when pushing to heroku

app/javascript/plugins/algoliasearch.js
I had to comment the indices used for development and add those for production.
I have already reindexed the database in production.
=> Change indices names for production

app/assets/stylesheets/components/_banner.scss, app/javascript/plugins/algoliasearch.js, app/views/pages/home.html.erb, app/views/tutors/index.html.erb
In the `tutors index` page I added a dataset attribute containing the current environment.
In the `algoliasearch script` I used this value to modify the Algolia index file names used for the search because the database in development and in production can be different. So it's best to use two different indices.
I also improved the responsiveness of the `landing` page.
=> Dynamic algolia indices and responsiveness

app/views/layouts/application.html.erb
Uncomment line to import css in javascript in `application.html.erb`
=> Fix problem with Flatpickr display on bookings new page

app/assets/stylesheets/bookings/_index.scss, app/assets/stylesheets/bookings/_main.scss, app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/config/_bootstrap_variables.scss, app/assets/stylesheets/config/_colors.scss, app/models/booking.rb, app/views/bookings/index.html.erb
- Modify bootstrap variables colour to match v4
- Refactor bookings index view and add style:
- create style template for booking card
- refactor conditions for booking's status
- Create status method of Booking model:
- it returns a hash with keys `class` and `message`
- use it in bookings index view and style
- Create new style partial for bookings index page and add some style
- Create a colour for each booking status and improve responsiveness
=> Improve bookings index

app/assets/stylesheets/bookings/_main.scss, app/assets/stylesheets/bookings/_show.scss, app/assets/stylesheets/components/_card.scss, app/controllers/bookings_controller.rb, app/controllers/lessons_controller.rb, app/models/booking.rb, app/views/bookings/index.html.erb, app/views/bookings/show.html.erb, config/routes.rb
* Created **new display** of bookings show page:
* Create a `status` method for **Booking model** that return the status of a booking instance as a hash containing 3 key/value pairs:
* the `class` key stores the class name for styling the status tag and the action button
* the `message` key stores the message to display on the action button
* the `action` key stores the route to go to when clicking on the action button
* Create 3 new **custom routes** nested in bookings:
* `/booking/:id/accept` for the tutor to accept a booking request
* `/booking/:id/pay` for the student to pay the booking
* `/booking/:id/cancel` for the tutor or student to cancel the booking
* Refactor the `update` method in **bookings controller**
* Refactor the `create` method in **lessons controller**
_Notes:_
* …
=> Improve booking show

app/assets/stylesheets/chats/_show.scss
forgot to push last commit before creating pull request
=> modify chats user banner style

app/assets/stylesheets/tutors/_login_signup_form.scss, app/assets/stylesheets/tutors/_main.scss, app/views/shared/_navbar.html.erb, app/views/students/registrations/new.html.erb, app/views/students/sessions/new.html.erb, app/views/students/shared/_links.html.erb, app/views/tutors/registrations/new.html.erb, app/views/tutors/sessions/new.html.erb, app/views/tutors/shared/_links.html.erb
I didn't add an amazing style but at least the forms look better now.
=> Add style to sign up and login forms

app/assets/stylesheets/application.scss, app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/payments/_main.scss, app/assets/stylesheets/payments/_new.scss, app/controllers/bookings_controller.rb, app/views/payments/new.html.erb
- Change message of button for payment on bookings show view
- Create style for new payment view
- Create new folder for payments style in stylesheets
=> Create style for new payment view

app/assets/stylesheets/application.scss, app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/wallets/_main.scss, app/assets/stylesheets/wallets/_show.scss, app/controllers/wallets_controller.rb, app/views/wallets/show.html.erb, db/seeds.rb
- wallets controller > show method: retrieve paid bookings from logged in tutor
- wallets > show view:
- display bookings informations
- add style
- seeds:
- change some bookings made by alice to random students
- change some bookings to pierre to random tutors
- create more paid bookings for wallets
- at the end update all wallets to store the total amount of paid bookings
=> Wallet design

app/controllers/wallets_controller.rb
- wallets controller > show method: order bookings by dates in descending order
=> Order wallet transactions

app/assets/stylesheets/components/_form.scss, app/assets/stylesheets/components/_main.scss, app/assets/stylesheets/components/_tab.scss, app/assets/stylesheets/tutors/_login_signup_form.scss, app/assets/stylesheets/tutors/_main.scss, app/views/students/sessions/new.html.erb, app/views/tutors/sessions/new.html.erb
When clicking on Login in the navbar, the user is sent to the student login as before.
However the form has now two tabs. So the user can switch to the tutor login and back on the same page !
I know it was not essential but it was getting annoying to login as a tutor for testing pruposes.
=> Login tabs

app/assets/stylesheets/application.scss, app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/components/_form.scss, app/assets/stylesheets/config/_fonts.scss, app/assets/stylesheets/job_posts/_index.scss, app/assets/stylesheets/job_posts/_main.scss, app/views/job_posts/index.html.erb
In **views > job_posts > index.html.erb**:
- Modified structure
In **stylesheets**:
- Changed body font from Work Sans to Lato
- Created new folder for job posts style, only index for now
- Added style for job posts index view, job posts cards and job posts search form
=> Refactor job posts index style

app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/components/_form.scss, app/assets/stylesheets/job_posts/_main.scss, app/assets/stylesheets/job_posts/_show.scss, app/views/comments/_comment.html.erb, app/views/comments/_form.html.erb, app/views/job_posts/show.html.erb
In views > job posts > **show.html.erb** and views > comments > _**comment.html.erb** and views > comments > **_form.html.erb**:
- refactor structure
In assets > **stylesheets**:
- add style for job posts show page
- add style for comments
- add style for new comment form
=> Refactor job posts show style
